### PR TITLE
Cleaning some of the code

### PR DESCRIPTION
**Pull request by Benliam12**
I felt bad. Depending on how motivated you guys are with this project, I might try to help.

### CODE REVIEW

**Comment by thegeek101** [comment]
Hello? Thanks for clearing the code, how do I update this version with your edits?

**Comment by thegeek101** [comment]
I was going to clear it up, anyway, but thanks! If you want to help, then you can comment here with any suggestions and I might make you an editor.... :)

**Comment by Benliam12** [comment]
> Hello? Thanks for clearing the code, how do I update this version with your edits?

You have to fix the conflicts (As i changed stuff in some files) After ward, you can merge my branch

**Comment by Benliam12** [comment]
I going to make a new pull request with your new version of code onto your master branch.

**Comment by thegeek101** [comment]
Hi, thanks! 😀 I already cleared up the images and CSS, don't worry. If you like, I can add you to the organisation as a member so you can suggest changes to the files. Should I? 👍

**Pull request closed without merging**
